base_path: "C:/Users/hugom/Downloads/convertor/"
packet_name: "packet.txt"
portal_folder: "map_portals"
binary_map_folder: "binary_maps"
map_folder: "maps"
map_monster_folder: "map_monster_placement"
recipe_file: "scroll.txt"
recipe_folder: "recipes"
language: "uk"